development:
  adapter: postgresql
  encoding: utf8
  database: food/development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: food/test
  username: postgres
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: food/production
  username: postgres
  password:
  host: localhost
  port: 5432
